services:
  grafana:
    user: root
    container_name: 'frcy-sqlassistant-app'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.1.1}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 127.0.0.1:3000:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/frcy-sqlassistant-app
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/frcy-sqlassistant-app

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.frcy-sqlassistant-app:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: frcy-sqlassistant-app
